sonar.projectKey=VictoriscominG_go-from-scratch-project-244
sonar.organization=victoriscoming

sonar.sources=.
sonar.exclusions=/*_test.go,/testdata/,/vendor/
sonar.tests=.
sonar.test.inclusions=/*_test.go

# main.go — только wiring, исключаем из метрики покрытия
sonar.coverage.exclusions=cmd/**

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8