sonar.projectKey=VictoriscominG_go-from-scratch-project-244
sonar.organization=victoriscoming

sonar.sources=.
sonar.exclusions=**/*_test.go,testdata/**,vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Исключения из метрики покрытия
sonar.coverage.exclusions=cmd/**,internal/testfixtures/fixtures.go

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
